### PR TITLE
fix: get proper parser name

### PR DESCRIPTION
**Pull request by hornyjailfish**
filetype not always equal parser name. Gives error for me on `tsx` files because its filetype `typescriptreact`

### CODE REVIEW

**Comment by roobert** [comment]
Thank you for PR!

Would it make sense to fail silently if no parser found?

**Comment by hornyjailfish** [comment]
i don't mind. Imo it should throw error at least in debug mode

**Comment by roobert** [comment]
In debug mode makes most sense to me 👍

**Comment by roobert** [comment]
Thank you again for the PR!

**Pull request merged**
